### ISSUE TITLE
Missing Code License

### ISSUE THREAD

**Issue by aliabdelkader** [lrettenberger/LLM_Political_Orientation#1]
Hi,

Thank you very much for the paper and the associated code. I would like to build upon it in my research.

Would you mind mentioning the license associated with this code ? maybe adding the license file to the repo if possible.

**Comment by lrettenberger** [comment]
Hi Ali,

I am very pleased that you are interested in our work! I have added the license. If you have any further questions, please do not hesitate to open another issue! :)

Best,
Luca
